DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS presentation;
DROP TABLE IF EXISTS concert;

CREATE TABLE person
(
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(60) NOT NULL,
    email      varchar(40) NOT NULL,
    pass       varchar(40) NOT NULL,
    role       varchar(10) NOT NULL
);

CREATE TABLE concert
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       varchar(30) NOT NULL,
    author      varchar(50) NOT NULL,
    description text        NOT NULL,
    image_path  text        NOT NULL
);

CREATE TABLE presentation
(
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    presentation_time timestamp not null,
    concert_id        bigint references concert (id),
    hall              varchar(30) not null
);

create table ticket
(
    presentation_id bigint not null references presentation(id) on delete set null,
    row integer not null check (row > 0),
    place integer not null check (place > 0),
    owner_id bigint references person(id) on delete set null,

    constraint pk_ticket primary key (presentation_id, row, place)
);