DROP TABLE IF EXISTS ticket;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS presentation;
DROP TABLE IF EXISTS concert;

CREATE TABLE person
(
    id         bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name varchar(20) NOT NULL,
    last_name  varchar(20),
    email      varchar(30) NOT NULL,
    pass       varchar(40) NOT NULL
);

CREATE TABLE concert
(
    id          bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title       varchar(20) NOT NULL UNIQUE,
    description text        NOT NULL
);

CREATE TABLE presentation
(
    id                bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    presentation_time timestamp not null,
    concert_id        bigint references concert (id)
);

create table ticket
(
    presentation_id bigint  not nullreferences presentation,
    row integer not null check (row > 0),
    place integer not null check (place > 0),
    owner_id bigint references person,

    constraint pk_ticket primary key (presentation_id, row, place)
);